#!/usr/bin/env bash
# scripts/preflight.sh — local reproduction of the CI gates before `git push`.
# Generated by ~/claude-config/scripts/gen-preflight.py from the workflows below;
# every command is the one CI runs. A step this file does not cover is a step
# that can only fail remotely — when a workflow step is added, regenerate or
# add it here in the same commit. ~/.claude/hooks/pre-push-preflight.sh runs
# `--quick` before every push and blocks on failure.
#
# usage: scripts/preflight.sh [--quick]   (--quick skips the test / bench suites)
set -euo pipefail
cd "$(dirname "$0")/.."

quick=0
[[ "${1:-}" == "--quick" ]] && quick=1

step() { printf '\n\033[1;34m== %s\033[0m\n' "$*"; }
# `cargo clippy` reuses fresh `cargo check` artifacts and then lints nothing;
# touching the crate roots invalidates only this repo's fingerprints.
relint() { git ls-files | grep -E '(^|/)src/(lib|main)\.rs$' | xargs -r touch; }
need() { command -v "$1" >/dev/null 2>&1 || { echo "missing tool: $1 ($2)" >&2; exit 1; }; }
has_toolchain() { rustup toolchain list | grep -q "^$1"; }

# Steps CI runs that this file cannot reproduce locally (they can only fail remotely):
#   - ci.yml:test:Strip the private optional path dep (alice-world / tts) (needs network / runner-only)

need actionlint "brew install actionlint"

step "ci.yml / fmt: Check formatting"
( export CARGO_TERM_COLOR="always"; cargo fmt -- --check )

step "ci.yml / actionlint: actionlint"
actionlint .github/workflows/*.yml

if [[ $quick -eq 1 ]]; then
  echo; echo "preflight --quick OK (test / bench suites skipped)"; exit 0
fi

step "ci.yml / test: Test (default features)"
( export CARGO_TERM_COLOR="always"; cargo test )

step "ci.yml / features: Test (cuda feature)"
# cudarc は dynamic-loading なので CUDA 不在の Mac でも compile / test できる。
# default features しか回していなかったため cuda 経路が E0425 で壊れていた事案の gate。
# cuda_matmul::tests は実 GPU を要求し、driver 不在だと cudarc が panic するので skip
( export CARGO_TERM_COLOR="always"; cargo test --lib --features cuda -- --skip cuda_matmul )

step "ci.yml / features: Check (qat-cuda, all bins)"
( export CARGO_TERM_COLOR="always"; cargo check --features qat-cuda --bins )

if command -v cargo-hack >/dev/null 2>&1; then
  step "ci.yml / features: Feature powerset (depth 2)"
  ( export CARGO_TERM_COLOR="always"; cargo hack check --lib --feature-powerset --depth 2 --exclude-features tts,blas-openblas )
else
  echo "  (skip) cargo-hack 未 install — CI 側の feature-powerset だけが gate になる: cargo install cargo-hack"
fi

echo; echo "preflight OK"
